version: '3.1'
services:
  read_all:
    image: hectorqin/reader
    container_name: reader #容器名 可自行修改
    restart: always
    ports:
      - 4396:8080 #4396端口映射可自行修改
    volumes:
      - /home/reader/logs:/logs #log映射目录 /home/reader/logs 映射目录可自行修改
      - /home/reader/storage:/storage #数据映射目录 /home/reader/storage 映射目录可自行修改
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - READER_APP_SECURE=true #开启登录鉴权，开启后将支持多用户模式
      - READER_APP_CACHECHAPTERCONTENT=true #开启缓存章节内容 V2.0
      - READER_APP_SECUREKEY=adminpwd  #管理员密码  建议修改
      - READER_APP_USERLIMIT=5 #用户上限,默认50
      - READER_APP_USERBOOKLIMIT=1000 #用户书籍上限,默认200
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    environment:
        - TZ=Asia/Shanghai
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: reader watchtower --cleanup --schedule "0 0 4 * * *"
    # 仅更新reader与watchtower容器,如需其他自行添加 '容器名' ,如:reader watchtower nginx
    # --cleanup 更新后清理旧版本镜像
    # --schedule 自动检测更新 crontab定时(限定6位crontab) 此处代表凌晨4点整
